require "language_pack/base"

# This file is automatically generated by rake
module LanguagePack
  class LanguagePack::Base
    VERSION_FILE = File.expand_path('../../../VERSION', __FILE__)
    BUILDPACK_VERSION = "v174"
  end
end
